### ISSUE TITLE
Could not locate the bindings file

### ISSUE THREAD

**Issue by belohlavek** [exponent/exp#11]
Trying to start exp with `exp start` resulted into this:

<details>
<summary>

View error</summary>

```
/usr/local/lib/node_modules/exp/node_modules/bindings/bindings.js:91
  throw err
  ^
Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/exp/node_modules/ref/build/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/build/Debug/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/build/Release/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/out/Debug/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/Debug/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/out/Release/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/Release/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/build/default/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/compiled/6.6.0/linux/x64/binding.node
    at bindings (/usr/local/lib/node_modules/exp/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/exp/node_modules/ref/lib/ref.js:5:47)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/exp/node_modules/ffi/lib/ffi.js:6:11)
```

</details>

Using Ubuntu (Linux subsystem for Windows 10)
Node version: 6.6.0
NPM version: 3.10.3

Any tips on what's going on?

**Comment by ide** [comment]
It looks like the issue is specific to Windows https://github.com/node-ffi/node-ffi/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20windows. Can you try running `npm install ffi` and seeing if you get an installation error?

**Comment by belohlavek** [comment]
Installed ffi and g++: same error

Should I open an issue on `node-ffi`'s repo? I still don't quite get what's going on 😆

**Comment by ide** [comment]
Can you paste the error in a code block here? That will make it clearer whether this is something we can fix in `exp` or `node-ffi` or somewhere else.

**Comment by belohlavek** [comment]
@ide Are you asking about the error I showed on the first comment, or do I need to get something else?

Here's the one on the first comment:

```
/usr/local/lib/node_modules/exp/node_modules/bindings/bindings.js:91
  throw err
  ^
Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/exp/node_modules/ref/build/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/build/Debug/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/build/Release/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/out/Debug/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/Debug/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/out/Release/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/Release/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/build/default/binding.node
 → /usr/local/lib/node_modules/exp/node_modules/ref/compiled/6.6.0/linux/x64/binding.node
    at bindings (/usr/local/lib/node_modules/exp/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/exp/node_modules/ref/lib/ref.js:5:47)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/exp/node_modules/ffi/lib/ffi.js:6:11)
```

Please let me know if I need to do anything else, and thanks for the support 😄

**Comment by dikaiosune** [comment]
@belohlavek I don't currently have a windows machine to reproduce this -- can you let us now if this is still an issue for you?

**Comment by belohlavek** [comment]
Just happened once and never got the error again, closing for now, thanks!
