### ISSUE TITLE
[exp] Unable to fetch new certificates

### ISSUE THREAD

**Issue by cameronbarker** [exponent/exp#16]
Ran across this error when trying to run `exp build:ios`.

Find a note @skevy had in the #help channel in exponentsjs slack where he stated it was due to too many certificates in my apple developer account.  After removing those it fixed the issue and moved onto building the ios package.

Be happy to pass along a pull request with a more descriptive error if you guys wanted.  Not too familiar with the whole process but if you could point me in the right direction happy to help.

Backtrace: 

```
Error: Unable to fetch new certificates.
    at Object._callee5$ (/Users/Jesse/Exponent/newuniverse/universe/dev/xdl/gulp/src/Credentials.js:123:15)
    at tryCatch (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
    at run (/usr/local/lib/node_modules/exp/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /usr/local/lib/node_modules/exp/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/exp/node_modules/core-js/library/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
```

**Comment by dikaiosune** [comment]
These error messages have been overhauled now -- please let us know if you run into other uninformative ones though!

**Comment by cameronbarker** [comment]
👍  @dikaiosune
