### ISSUE TITLE
Building android apk fails

### ISSUE THREAD

**Issue by Joshuabaker2** [exponent/exp#25]
- Running sdk 12.0.0
- Running in the simulator/emulator for both iOS and Android works. 

However, when I run 
`exp build:android`
I get the following output: 

```
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.

? Would you like to upload a keystore or have us generate one for you?
If you don't know what this means, let us handle it! :)
 false
[exp] Starting build process...
[exp] Cannot read property 'ids' of undefined
TypeError: Cannot read property 'ids' of undefined
    at AndroidBuilder._callee4$ (/usr/local/lib/node_modules/exp/build/commands/build/BaseBuilder.js:270:31)
    at tryCatch (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

This also occurs if I upload my own keystore. I've tried uninstalling and reinstalling exp to no avail. Running Mac OS El Capitan.

**Comment by Joshuabaker2** [comment]
The issue here was a lack of reading the documentation - I neglected the first step, running `exp start`.

**Comment by ccheever** [comment]
We should make that flow easier and clearer. Glad you resolved the issue.
CDC
