### ISSUE TITLE
[exp] Error: UserSettings.setAsync is not a function

### ISSUE THREAD

**Issue by Swistaku** [exponent/exp#9]
Hey guys, I've just tried out exp tool on linux and it seems it's not starting. It creates an dummy app and when I want to `exp start` it it hangs, and in logs we can see several errors:

```
exp-serve/dummy:8f14906c-0 (err): TypeError: UserSettings.setAsync is not a function
exp-serve/dummy:8f14906c-0 (err):     at _callee2$ (/usr/lib/node_modules/exp/node_modules/xdl/build/Session.js:55:33)
exp-serve/dummy:8f14906c-0 (err):     at tryCatch (/usr/lib/node_modules/exp/node_modules/xdl/node_modules/babel-runtime/regenerator/runtime.js:88:40)
exp-serve/dummy:8f14906c-0 (err):     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/lib/node_modules/exp/node_modules/xdl/node_modules/babel-runtime/regenerator/runtime.js:341:22)
exp-serve/dummy:8f14906c-0 (err):     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/lib/node_modules/exp/node_modules/xdl/node_modules/babel-runtime/regenerator/runtime.js:121:21)
exp-serve/dummy:8f14906c-0 (err):     at step (/usr/lib/node_modules/exp/node_modules/xdl/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
exp-serve/dummy:8f14906c-0 (err):     at /usr/lib/node_modules/exp/node_modules/xdl/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
exp-serve/dummy:8f14906c-0 (err):     at new Promise (/usr/lib/node_modules/exp/node_modules/xdl/node_modules/core-js/library/modules/es6.promise.js:193:7)
exp-serve/dummy:8f14906c-0 (err):     at /usr/lib/node_modules/exp/node_modules/xdl/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
exp-serve/dummy:8f14906c-0 (err):     at setClientIdAsync (/usr/lib/node_modules/exp/node_modules/xdl/build/Session.js:68:16)
exp-serve/dummy:8f14906c-0 (err):     at Object._callee$ (/usr/lib/node_modules/exp/node_modules/xdl/build/Session.js:31:20)
```

also got this naming collision:

```
exp-serve/dummy:8f14906c-0 (out): Error building DependencyGraph:
exp-serve/dummy:8f14906c-0 (out):  Error: Naming collision detected: /home/swistak/Labs/react-native/dummy/node_modules/react-native/Libraries/vendor/fbjs/CSSCore.js collides with /home/swistak/Labs/react-native/dummy/node_modules/fbjs/lib/CSSCore.js
```

I am not sure if it's supposed to run on linux, but if you need someone who can test it (I'm just getting started with JS/React so I can offer a bit code help) I voluteer :smile:

**Comment by ccheever** [comment]
Hi-

I think it should be possible to make it run on Linux but we haven't tested it except on Mac, so there are probably a few things we need to debug before it will work smoothly. I'm not sure when we can get to this, but I'll make a task. 

If you end up debugging anything, we'll happily accept patches in the meantime until we can get to it.

Thanks!

**Comment by dikaiosune** [comment]
exp should work well on linux now. Please reopen if you're still having issues though.
